version: "3.0"
services:
  postgres:
    image: machadolab-db
    ports:
      - "5432:5432"

  spring-boot-app:
    image: machadolab-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  nextjs-ui:
    image: machadolab-client
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-app
