version: "3.0"
services:
  postgres:
    build:
      context: ./data
    ports:
      - "5432:5432"

  spring-boot-app:
    build:
      context: ./machadolabserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  nextjs-ui:
    build:
      context: ./machadolabclient
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-app
